name: deploy_frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure CLI using Service Principal
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo $AZURE_CREDENTIALS > azure_credentials.json
          az login --service-principal --username $(jq -r .clientId azure_credentials.json) --password $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

      - name: Upload to Azure Storage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        run: |
          az storage blob upload-batch --account-name $AZURE_STORAGE_ACCOUNT --destination \$web --source frontend/ --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "azureresprof" --name "azureresendpoint" --resource-group "ResAPI"

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
